### ISSUE TITLE
how to debug this issue

### ISSUE THREAD

**Issue by ofthewood** [xolvio/chimp#317]
After installation ( npm install -g chimp ) , this simple test returns me an error : 

```
browser.url('https://evernote.com/intl/fr/');
browser.click('//button[contains(., "Connex")]');

```
the error msg : 
      Error: Underlying driver does not implement advanced user interactions yet.
          - - - - -

I'm on windows 7  / chrome Version 49.0.2623.87 m

do you any advice to debug this issue ?

**Comment by ricoli** [comment]
Same here, using newest version, 0.31.0 on chrome 49 running on linux

**Comment by area** [comment]
Same with 0.31.0 on Chrome 43 (CircleCI default) on Linux. Tests work on 0.30.0.

**Comment by ofthewood** [comment]
Thks

**Comment by Sanjo** [comment]
This is fixes in 0.31.1.

@ofthewood You can debug such an issue with `--debug`. Then you see the selenium protocol log and more output from Chimp.

**Comment by ofthewood** [comment]
0.31.1 version gives other issues like
 ```
Error: 
unknown error: Element is not clickable at point (84, 123). Other element would receive the click: 

```
Tests work on 0.30.0.
