### ISSUE TITLE
Running Chimp in cucumber mode on windows produces an error

### ISSUE THREAD

**Issue by kwright1** [xolvio/chimp#432]
#####  Expected behaviour
Chimp starts up without issue.

I think this might be a re-manifestation of an old problem where some cucumber stuff was splitting on ':' for absolute paths

#####  Actual behaviour
module.js:442
    throw err;
    ^

Error: Cannot find module 'C'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Array.forEach (native)
    at Object.initializer (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:22:25)
    at Object.Library (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\support_code\library.js:120:25)
    at Object.getSupportCodeLibrary (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\cli\configuration.js:126:32)
    at Object.getSupportCodeLibrary (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\runtime.js:43:46)

##### Steps to reproduce the problem

I just did a fresh install of node + chimp and tried to run chimp --watch

#####  Used version

* Chimp: 0.39.0
* Node.js: 6.3.1
* Operation system: Windows

#####  Console / Log Output

$ ./node_modules/.bin/chimp --watch
[chimp] Watching features with tagged with @focus,@dev,@watch

[chimp] Running...
module.js:442
    throw err;
    ^

Error: Cannot find module 'C'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Array.forEach (native)
    at Object.initializer (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:22:25)
    at Object.Library (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\support_code\library.js:120:25)
    at Object.getSupportCodeLibrary (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\cli\configuration.js:126:32)
    at Object.getSupportCodeLibrary (C:\Users\Kyle\webdriverio-test\node_modules\cucumber\lib\cucumber\runtime.js:43:46)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by GeeChao** [comment]
Also getting the same error on my end on Windows. Is there currently a workaround fix for this issue?

**Comment by GeeChao** [comment]
Have tried version 0.34 as suggested by @samhatoum and is currently working on Windows wth version 4.4.7 of NodeJS

**Comment by MacDennis76** [comment]
Any idea when this issue will be fixed? Tried the latest version, does not work on Windows 10. Reverting to 0.34 does work.

**Comment by samhatoum** [comment]
@MacDennis76 which version of node? Have you tried with Node 6.5.0?

**Comment by mmcculloch15** [comment]
On Windows 7 I'm getting the same error if I update to any version of chimp past 0.38, and any version of node past 5.12.0.

**Comment by cloughney** [comment]
Same issue here, encountered on multiple machines with Windows 10. Have tried on node v5.11.0 and v6.5.0 with the latest version of chimp. Everything works correctly with chimp v0.34.

**Comment by pkoppula15** [comment]
I am having the same Issue. Any idea when this would be fixed ?  Works fine with 0.34 but I am missing new features of the latest version.

**Comment by Sanjo** [comment]
This could be the absolute path that we pass to cucumber for the JavaScript transpilation. https://github.com/xolvio/chimp/blob/91f9daa5e1cb5962cdae7b27325b39b566902325/src/bin/default.js#L34

**Comment by samhatoum** [comment]
you can test this by overriding the compiler option in a config file

**Comment by james-mcelwain** [comment]
Specifying the absolute path in my custom configuration doesn't help. I'm successfully able to `require` babel-register.js using the path returned by `path.resolve` in the Node REPL, but it still chokes when passed to to cucumber. It looks like cucumber/cli is just mapping require onto the path, so I assume the path is getting mangled somewhere in cucumber. Going to investigate a little more and report back.

**Comment by samhatoum** [comment]
awesome, thank you @james-mcelwain

**Comment by Sanjo** [comment]
Here is the fix: https://github.com/xolvio/cucumber-js/commit/7fdbc5ca6e7d5a82e40b18feb69c1f4bc4eeda93. For some reason it is not in the current release anymore.

**Comment by james-mcelwain** [comment]
@Sanjo Awesome! Any chance you could get this merged to close this? We're trying to get a proof of concept for some automated testing stuff using Chimp and this has been a big annoyance for us. Thanks!

**Comment by pkoppula15** [comment]
Any update on the new build with the fix ?

**Comment by samhatoum** [comment]
Fixed in 0.41.0

**Comment by samhatoum** [comment]
@pkoppula15 and @james-mcelwain please let me know if this works for you

**Comment by pkoppula15** [comment]
Thanks @samhatoum , I'll give a shot and let you know.

**Comment by pkoppula15** [comment]
It works now. Thanks @samhatoum

**Comment by MacDennis76** [comment]
Yes, confirmed working!
